### ISSUE TITLE
Missing index.js

### ISSUE THREAD

**Issue by stacy-rendall** [g1eb/angular-scroll-events#1]
package.json refers to main as index.js, but this is not in the package. Should be:

require('./dist/scroll-events.min.js');
module.exports = 'g1b.scroll-events';

**Comment by g1eb** [comment]
Hi! Thanks for catching that, does it give you warnings when using it with npm?

I would probably just change the package.json to point to the minified file instead.

**Comment by stacy-rendall** [comment]
How you have done it in https://github.com/g1eb/angular-datetime-inputs seemed to work fine

**Comment by g1eb** [comment]
Cool, closing this issue then :)
